### PR TITLE
Just pulling hpcugent/develop

### PR DESCRIPTION
**Pull request by rjeschmi**

### CODE REVIEW

**Comment by rjeschmi** [comment]
I've done some tests on the PGI toolchain and haven't seen any issues.

I'd like to help get this merged.

I think that @boegel will want it pulled up to date with develop (so that the automatic tests don't fail). Hopefully we can get this merged into the PR soon, or perhaps I should open a new PR? What do you think @bartoldeman ?

**Comment by boegel** [comment]
@rjeschmi: if @bartoldeman doesn't have time to follow up, a wrapper PR that continues where he left off makes sense to me

syncing with develop is often needed, indeed

**Comment by bartoldeman** [comment]
Hi,

I'll comment later today. I also wrote a few basic toolchain easyconfigs (pompi-2015b.eb and pmvapich2-2015b.eb) that I could contribute.

Bart

**Comment by rjeschmi** [comment]
I have a pvamich as well. Do you have a branch for yours?

I have a few deps built to build ioapi

**Comment by bartoldeman** [comment]
Hi,

I've rebased the my pgi branch and also added pompi and pmvapich2 branches. The MVAPICH2 eb for pgi has some local configure settings so is still a draft (local-only). I will submit seperate PRs for those.

I've also added a new pgi eb based on GCC 4.9.3 instead of 4.9.2. We could delete the 4.9.2 one if you like.

Bart

**Comment by rjeschmi** [comment]
My pgimvapich is here:

https://github.com/rjeschmi/easybuild-easyconfigs/commit/f94df03ef6fc3bbaddb218ac67bf3ce2e19ed881

(I dont' like the names being too short :p )

**Comment by rjeschmi** [comment]
Everything looks good. 

I'm not fussy either way on GCC. 

I'll close this and move my comments onto the main PR (maybe framework?)

**Pull request closed without merging**
